### ISSUE TITLE
How do you launch the script?

### ISSUE THREAD

**Issue by gemcosta** [Dealman/Destiny2SoloMode#1]
I checked the ReadMe but it doesn't have any information about what file to run or what command to use to launch this.

**Comment by Dealman** [comment]
Sorry for the late reply! Did you download the source code or the built binary file?

If you go to the releases page there should be a link to download a built executable file. Then you simply run that.

If you downloaded the source you'll have to open the project in Visual Studio and build it. 🙂

**Comment by gemcosta** [comment]
Ah! Now I see the executable, thank you for clarifying this for me. And thanks for creating this code :D
